### PR TITLE
Rewrite without dependencies

### PR DESCRIPTION
**Pull request by tilgovi**
Use a more straightforward and symmetrical algorithm by abstracting the
traversals that find leaf nodes within the range over the range offsets
and a step traversal step function.

### CODE REVIEW

**Comment by tilgovi** [comment]
Hi, @TooTallNate.

I studied this problem for the past several days trying to update and simplify openannotation/xpath-range because I wasn't satisfied with the normalization code there. It seemed a bit ad-hoc to me.

When I went looking for other implementations, I found yours. Similarly, I found the description of the algorithm a bit complex.

After sitting down with the problem for some time I've devised an algorithm that seems to pass both test suites and I propose to merge it here in replace of the implementation you've got.

I hope it's well commented and well described enough already, so I won't say more here unless you've got questions.

I haven't touched the tests at all. They all pass.

Coverage is higher than it was and I can see just three statements untested.
1. An empty node before a sibling boundary.
   `<b>foo<br/></b><i>bar</i>` with the range starting between the `B` and `I`.
2. Traversal running off the end of the document.
   Not sure what we want to happen here.
3. Traversal running off the beginning of the document.
   Again, not sure what we should do.

Thoughts, feelings?

**Comment by tilgovi** [comment]
Also, I suspect this should pass in IE8, even.

**Comment by TooTallNate** [comment]
Wow this is really awesome! Give me some time to review, but no deps + all tests passing seems like a 100% win to me. Thanks @tilgovi!

**Comment by tilgovi** [comment]
Thanks!

Take your time reviewing it. Also, note that the Sauce Labs tests won't pass with the PR due to not having the credentials.

Really nice bunch of libraries you've got building up under webmodules.

Lots of little things I'm noting:
- openannotation/xpath-range is not unlike webmodules/frozen-range, except it uses XPath rather than name-less node indexes
- similarity between webmodules/find-within and tilgovi/dom-seek
- My `documentForward()` function here could easily become an IE8 polyfill for `createNodeIterator`
- I've got a split function much like timdown/rangy in openannotation/xpath-range, splitting a range text node boundary at its offset, that maybe I should package separately
- I don't know about the span hack in webmodules/bounding-client-rect, but if it works for text nodes we could do something like what I did here: https://github.com/hypothesis/h/blob/master/h/static/scripts/annotator/highlighter.coffee#L35

Anyway, so many nice things. I wish I had found them sooner!

**Comment by tilgovi** [comment]
Err, I misspoke. `find-within` maybe obviates the `firstLeaf` and `lastLeaf` helpers I've got in this PR. It's webmodules/range-at-index that has similarity to tilgovi/dom-seek / tilgovi/dom-anchor-text-position and I've got similar to webmodules/dom-regexp-match in tilgovi/dom-anchor-text-quote except using bitap instead of regex.

**Comment by tilgovi** [comment]
Bump?

**Comment by bboydflo** [comment]
it would be nice to merge this :)

**Comment by tilgovi** [comment]
@TooTallNate any interest still?

**Pull request closed without merging**
